spring.application.name=ramossomar

# Servidor
server.address=localhost
server.port=7000

# Banco de dados MySQL
spring.datasource.url=jdbc:mysql://187.127.43.161:3306/db_ramossomar?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=C0nV3Mu2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JSON em snake_case (Jackson 3 / Spring Boot 4)
spring.jackson.datatype.datetime.write-dates-as-timestamps=false

# JWT
app.jwt.secret=RamosSomarJwtSecretKey2026ConvertixSegurancaMuitoForteParaAssinaturaHS256
app.jwt.issuer=ramossomar-api

# Springdoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

# Abrir Swagger no navegador ao iniciar a aplicação
app.swagger.abrir-navegador=true
